# --- 下载设置 ---
dir=/home/nazze/Downloads
file-allocation=falloc
continue=true
max-connection-per-server=16
split=16

# --- DHT 网络设置 ---
# 开启 IPv4 DHT 运行，有助于寻找磁力链接位元数据
enable-dht=true
# 开启 IPv6 DHT 运行
enable-dht6=true
# DHT 网络监听端口
dht-listen-port=6881-6999
# 本地节点查找，用于发现局域网内的下载者
bt-enable-lpd=true
# 种子交换机制，允许 Peers 之间交换彼此已知的节点信息
enable-peer-exchange=true

# --- Tracker 设置 ---
bt-tracker=udp://tracker.opentrackr.org:1337/announce,,udp://open.demonii.com:1337/announce,,udp://open.stealth.si:80/announce,,udp://wepzone.net:6969/announce,,udp://tracker.wepzone.net:6969/announce,,udp://tracker.torrent.eu.org:451/announce,,udp://tracker.theoks.net:6969/announce,,udp://tracker.srv00.com:6969/announce,,udp://tracker.qu.ax:6969/announce,,udp://tracker.darkness.services:6969/announce,,udp://tracker.corpscorp.online:80/announce,,udp://t.overflow.biz:6969/announce,,udp://opentracker.io:6969/announce,,udp://open.dstud.io:6969/announce,,udp://leet-tracker.moe:1337/announce,,udp://explodie.org:6969/announce,,udp://exodus.desync.com:6969/announce,,udp://bittorrent-tracker.e-n-c-r-y-p-t.net:1337/announce,,udp://6ahddutb1ucc3cp.ru:6969/announce,,https://tracker.zhuqiy.com:443/announce,
