font_size  16.0

hide_window_decorations yes
linux_display_server wayland
remember_window_size   yes
window_padding_width   8
window_margin_width    0
window_border_width    2.0
# active_border_color    #d8d8d8
# inactive_border_color  #6a7984

# 布局、回滚缓冲、通知等
enabled_layouts splits,stack
scrollback_lines 5000
enable_audio_bell no
update_check_interval 0
allow_remote_control yes

# 背景透明度
background_opacity 0.9

# 标签栏样式 (powerline / default / compact / ...)
tab_bar_style powerline
tab_powerline_style slanted


# OS specific
# macos_option_as_alt no

# Window resizing
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter

# Font sizes
# map  cmd+0      change_font_size all 0
map  cmd+equal   change_font_size all +1.0
map  cmd+minus  change_font_size all -1.0

# Move by words
map  alt+left   send_text all \x1b\x62
map  alt+right  send_text all \x1b\x66

# 窗口与标签管理
# map ctrl+shift+t new_tab_with_cwd
map ctrl+t launch --type=tab --cwd=current
map ctrl+enter launch --location=vsplit --cwd=current
map ctrl+shift+enter launch --location=hsplit --cwd=current
# map alt+n next_tab

map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9



# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="Maple Mono NF CN"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
